{ pkgs, lib, pythonSet, system, module ? ./module.nix }:

let
  pkg = pythonSet."agenix-manager";

  stubOptions = {
    age.secrets = lib.mkOption { type = lib.types.attrsOf lib.types.raw; default = {}; };
    age.identityPaths = lib.mkOption { type = lib.types.listOf lib.types.str; default = []; };
    environment.systemPackages = lib.mkOption { type = lib.types.listOf lib.types.package; default = []; };
    system.activationScripts = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule {
        options = {
          text = lib.mkOption { type = lib.types.lines; };
          deps = lib.mkOption { type = lib.types.listOf lib.types.str; default = []; };
        };
      });
      default = {};
    };
  };

  testManifest = pkgs.writeText "secrets-manifest.json" (builtins.toJSON {
    version = 1;
    secrets = [
      { name = "t1"; scope = "systems"; }
      { name = "t2"; scope = "all"; owner = "postgres"; group = "postgres"; }
    ];
  });

  evalTest = lib.evalModules {
    modules = [
      ({ lib, ... }: { options = stubOptions; })
      { imports = [ module ]; }
      {
        agenixManager = {
          enable = true;
          manifestPath = "${testManifest}";
          secretsPath = "/test/secrets";
          keys.systems = [ "ssh-ed25519 AAAA...testkey" ];
          keys.users = [ "ssh-ed25519 AAAA...userkey" ];
          identities = [ "/etc/ssh/ssh_host_ed25519_key" ];
          package = pkg;
        };
      }
    ];
    specialArgs = { inherit pkgs; };
  };

  expectedContent = ''
    # Auto-generated by agenixManager NixOS module — do not edit by hand.
    # Regenerated on every nixos-rebuild switch.
    {
      "t1.age".publicKeys = [ "ssh-ed25519 AAAA...testkey" ];
      "t2.age".publicKeys = [ "ssh-ed25519 AAAA...testkey" "ssh-ed25519 AAAA...userkey" ];
    }
  '';

  secretsNixSmokeTest = pkgs.runCommand "secrets-nix-smoke" {
    nativeBuildInputs = [ pkgs.nix ];
  } ''
    content='${lib.escapeShellArg evalTest.config.agenixManager.secretsNixContent}'
    echo "$content" | ${pkgs.nix}/bin/nix-instantiate --eval --strict --stdin 2>/dev/null || {
      echo "FAIL: secrets.nix content is not valid Nix"
      exit 1
    }
    touch "$out"
  '';

  secretsNixDriftTest = pkgs.runCommand "secrets-nix-drift" {} ''
    actual='${lib.escapeShellArg evalTest.config.agenixManager.secretsNixContent}'
    expected='${lib.escapeShellArg expectedContent}'
    diff <(echo "$expected") <(echo "$actual") || {
      echo "FAIL: secrets.nix content has drifted from expected reference"
      exit 1
    }
    touch "$out"
  '';

  missingManifestTest = let
    evalMissing = lib.evalModules {
      modules = [
        ({ lib, ... }: { options = stubOptions; })
        { imports = [ module ]; }
        {
          agenixManager = {
            enable = true;
            manifestPath = "/nonexistent/manifest.json";
            secretsPath = "/test/secrets";
            keys.systems = [ "ssh-ed25519 AAAA...testkey" ];
            identities = [ "/etc/ssh/ssh_host_ed25519_key" ];
            package = pkg;
          };
        }
      ];
      specialArgs = { inherit pkgs; };
    };
  in
    pkgs.runCommand "missing-manifest-test" {} ''
      secrets=${
        lib.escapeShellArg (builtins.toJSON evalMissing.config.agenixManager.cliConfig.secrets)
      }
      if [ "$secrets" != "[]" ]; then
        echo "FAIL: expected empty secrets list when manifest is missing, got: $secrets"
        exit 1
      fi
      touch "$out"
    '';

in {
  build = pkg;

  venv = pythonSet.mkVirtualEnv "app-env" { agenix-manager = [ ]; };

  secrets-nix-smoke = secretsNixSmokeTest;

  secrets-nix-drift = secretsNixDriftTest;

  missing-manifest = missingManifestTest;
}
