{ config, lib, pkgs, ... }:
let
  cfg = config.agenixManager;

  resolveKeys = scope:
    if builtins.hasAttr scope cfg.keyGroups then cfg.keyGroups.${scope}
    else throw "agenixManager: unknown key scope '${scope}'";

  resolveSecretKeys = s:
    if builtins.isList s.keys then s.keys
    else resolveKeys s.keys;

  secretSubmodule = lib.types.submodule {
    options = {
      name  = lib.mkOption { type = lib.types.str; description = "Secret name, referenced as config.age.secrets.<name>.path"; };
      keys  = lib.mkOption {
        type = lib.types.either lib.types.str (lib.types.listOf lib.types.str);
        default = "all";
        description = ''
          Key scope name or list of literal SSH public keys.
          Scope names resolve to key groups defined in agenixManager.keyGroups.
          Built-in scopes: all, systems, users, other.
        '';
      };
      owner = lib.mkOption { type = lib.types.str; default = "root"; };
      group = lib.mkOption { type = lib.types.str; default = "root"; };
      mode  = lib.mkOption { type = lib.types.str; default = "0400"; };
    };
  };

  defaultKeyGroups = {
    systems = cfg.keys.systems;
    users   = cfg.keys.users;
    other   = cfg.keys.other;
    all     = cfg.keys.systems ++ cfg.keys.users ++ cfg.keys.other;
  };

in {
  options.agenixManager = {

    enable = lib.mkEnableOption "agenixManager declarative secrets";

    secretsPath = lib.mkOption {
      type = lib.types.path;
      description = ''
        Absolute path to the directory containing .age files.
        Example: ./secrets.
      '';
    };

    keys = {
      systems = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        description = "SSH public keys for NixOS host system identities (ssh_host_ed25519_key.pub content)";
      };
      users = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        description = "SSH public keys for human user identities";
      };
      other = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        description = "SSH public keys for any other identity (CI, hardware tokens, etc.)";
      };
    };

    keyGroups = lib.mkOption {
      type = lib.types.attrsOf (lib.types.listOf lib.types.str);
      default = defaultKeyGroups;
      defaultText = lib.literalMD "`{ systems = cfg.keys.systems; users = cfg.keys.users; other = cfg.keys.other; }`";
      description = ''
        Named key groups for secret encryption scopes.
        Built-in groups (systems, users, other) are defined automatically.
        Additional groups can be added for custom scopes:

        ```
        agenixManager.keyGroups = {
          deployment = cfg.keys.systems ++ [ "ssh-ed25519 AAAA..." ];
        };
        ```
      '';
    };

    identities = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      description = ''
        Runtime paths to SSH private keys used for decryption.
        These are passed to age.identityPaths. Use string paths (not
        Nix paths) to avoid copying private keys to the Nix store.
        Example: [ "/etc/ssh/ssh_host_ed25519_key" ]
      '';
    };

    secrets = lib.mkOption {
      type = lib.types.listOf secretSubmodule;
      default = [];
      description = ''
        List of secrets to manage. Multiple module imports append; they never
        overwrite. Each entry becomes a config.age.secrets.<name> binding.
      '';
    };

    cliConfig = lib.mkOption {
      internal = true;
      readOnly = true;
      type = lib.types.attrs;
      description = "Computed CLI configuration for agenix-manager CLI consumption via nix eval";
    };

    secretsNixContent = lib.mkOption {
      internal = true;
      readOnly = true;
      type = lib.types.str;
      description = "Computed secrets.nix content for drift checking and activation.";
    };

  };

  config = lib.mkIf cfg.enable {

    age.secrets = lib.listToAttrs (map (s: lib.nameValuePair s.name {
      file  = "${cfg.secretsPath}/${s.name}.age";
      owner = s.owner;
      group = s.group;
      mode  = s.mode;
    }) cfg.secrets);

    age.identityPaths = cfg.identities;

    agenixManager.secretsNixContent = let
      renderKeyList = keys:
        "[ " + (lib.concatMapStringsSep " " (k: "\"${k}\"") keys) + " ]";
      renderEntry = s:
        "  \"${s.name}.age\".publicKeys = ${renderKeyList (resolveSecretKeys s)};";
      entries = lib.concatStringsSep "\n" (map renderEntry cfg.secrets);
    in ''
      # Auto-generated by agenixManager NixOS module — do not edit by hand.
      # Regenerated on every nixos-rebuild switch.
      {
      ${entries}
      }
    '';

    system.activationScripts.agenixManagerSecretsNix = let
      secretsNixFile = pkgs.writeText "secrets.nix" cfg.secretsNixContent;
      cliConfigFile = pkgs.writeText "agenix-manager-cache.json" (builtins.toJSON cfg.cliConfig);
      keysSnapshotFile = pkgs.writeText "keys-snapshot.json" (
        builtins.toJSON (lib.listToAttrs (map (s:
          lib.nameValuePair s.name (resolveSecretKeys s)
        ) cfg.secrets))
      );
    in {
      text = ''
        echo "[agenixManager] Writing secrets.nix -> /etc/agenix/secrets.nix"
        echo "[agenixManager] Writing CLI cache   -> /etc/agenix/agenix-manager-cache.json"
        echo "[agenixManager] Writing keys snapshot -> /etc/agenix/keys-snapshot.json"
        mkdir -p /etc/agenix
        cp ${secretsNixFile} /etc/agenix/secrets.nix
        cp ${cliConfigFile} /etc/agenix/agenix-manager-cache.json
        cp ${keysSnapshotFile} /etc/agenix/keys-snapshot.json
        chmod 644 /etc/agenix/agenix-manager-cache.json /etc/agenix/keys-snapshot.json
      '';
      deps = [];
    };

    agenixManager.cliConfig = {
      secretsPath      = toString cfg.secretsPath;
      secretsNixPath   = "/etc/agenix/secrets.nix";
      keysSnapshotPath = "/etc/agenix/keys-snapshot.json";
      identities       = cfg.identities;
      keys             = cfg.keyGroups // { all = cfg.keyGroups.systems ++ cfg.keyGroups.users ++ cfg.keyGroups.other; };
      secrets = map (s: {
        inherit (s) name owner group mode;
        scope = if builtins.isList s.keys then "custom" else s.keys;
        keys  = resolveSecretKeys s;
        file  = "${toString cfg.secretsPath}/${s.name}.age";
      }) cfg.secrets;
    };

  };
}
