{ config, lib, pkgs, ... }:
let
  cfg = config.agenixManager;

  resolveKeys = scope:
    if scope == "all"     then cfg.keys.systems ++ cfg.keys.users ++ cfg.keys.other
    else if scope == "systems" then cfg.keys.systems
    else if scope == "users"   then cfg.keys.users
    else if scope == "other"   then cfg.keys.other
    else throw "agenixManager: unknown key scope '${scope}'. Valid: all systems users other";

  secretSubmodule = lib.types.submodule {
    options = {
      name  = lib.mkOption { type = lib.types.str; description = "Secret name, referenced as config.age.secrets.<name>.path"; };
      keys  = lib.mkOption { type = lib.types.str; default = "all"; description = "Key scope for encryption: all | systems | users | other"; };
      owner = lib.mkOption { type = lib.types.str; default = "root"; };
      group = lib.mkOption { type = lib.types.str; default = "root"; };
      mode  = lib.mkOption { type = lib.types.str; default = "0400"; };
    };
  };

in {
  options.agenixManager = {

    enable = lib.mkEnableOption "agenixManager declarative secrets";

    secretsPath = lib.mkOption {
      type = lib.types.path;
      description = ''
        Absolute path to the directory containing .age files and the
        auto-generated secrets.nix. This should be inside your nixos-config
        repo, e.g. ./secrets.
      '';
    };

    flakeRoot = lib.mkOption {
      type = lib.types.path;
      description = ''
        Absolute path to the root of your nixos-config flake. Used by the CLI
        to locate the flake for `nix eval` and for the activation script to
        know where to write secrets.nix.
      '';
    };

    keys = {
      systems = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        description = "SSH public keys for NixOS host system identities (ssh_host_ed25519_key.pub content)";
      };
      users = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        description = "SSH public keys for human user identities";
      };
      other = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        description = "SSH public keys for any other identity (CI, hardware tokens, etc.)";
      };
    };

    identities = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      description = ''
        Runtime paths to SSH private keys used for decryption.
        These are passed to age.identityPaths. Use string paths (not
        Nix paths) to avoid copying private keys to the Nix store.
        Example: [ "/etc/ssh/ssh_host_ed25519_key" ]
      '';
    };

    secrets = lib.mkOption {
      type = lib.types.listOf secretSubmodule;
      default = [];
      description = ''
        List of secrets to manage. Multiple module imports append; they never
        overwrite. Each entry becomes a config.age.secrets.<name> binding.
      '';
    };

    cliConfig = lib.mkOption {
      internal = true;
      readOnly = true;
      type = lib.types.attrs;
      description = "Computed CLI configuration for agenix-manager CLI consumption via nix eval";
    };

  };

  config = lib.mkIf cfg.enable {

    age.secrets = lib.listToAttrs (map (s: lib.nameValuePair s.name {
      file  = "${cfg.secretsPath}/${s.name}.age";
      owner = s.owner;
      group = s.group;
      mode  = s.mode;
    }) cfg.secrets);

    age.identityPaths = cfg.identities;

    system.activationScripts.agenixManagerSecretsNix = {
      text = let
        secretsNixContent = let
          keyGroups = {
            all     = cfg.keys.systems ++ cfg.keys.users ++ cfg.keys.other;
            systems = cfg.keys.systems;
            users   = cfg.keys.users;
            other   = cfg.keys.other;
          };
          renderKeyList = keys:
            "[ " + (lib.concatMapStringsSep " " (k: "\"${k}\"") keys) + " ]";
          renderEntry = s:
            "  \"${s.name}.age\".publicKeys = ${renderKeyList keyGroups.${s.keys}};";
          entries = lib.concatStringsSep "\n" (map renderEntry cfg.secrets);
        in ''
          # Auto-generated by agenixManager NixOS module — do not edit by hand.
          # Regenerated on every nixos-rebuild switch.
          {
          ${entries}
          }
        '';
        secretsNixFile = pkgs.writeText "secrets.nix" secretsNixContent;
      in ''
        echo "[agenixManager] Writing secrets.nix to ${toString cfg.secretsPath}"
        cp ${secretsNixFile} ${toString cfg.secretsPath}/secrets.nix
      '';
      deps = [];
    };

    agenixManager.cliConfig = {
      secretsPath = toString cfg.secretsPath;
      flakeRoot   = toString cfg.flakeRoot;
      identities  = cfg.identities;
      keys = {
        systems = cfg.keys.systems;
        users   = cfg.keys.users;
        other   = cfg.keys.other;
        all     = cfg.keys.systems ++ cfg.keys.users ++ cfg.keys.other;
      };
      secrets = map (s: {
        inherit (s) name keys owner group mode;
        file = "${toString cfg.secretsPath}/${s.name}.age";
      }) cfg.secrets;
    };

  };
}
