from __future__ import annotations

from pathlib import Path

from .config import NixConfig


def render_secrets_nix(cfg: NixConfig) -> str:
    lines = ["# Auto-generated by agenix-manager -- do not edit by hand.", "{"]
    for secret in cfg.secrets:
        key_str = " ".join(f'"{k}"' for k in secret.keys)
        lines.append(f'  "{secret.name}.age".publicKeys = [ {key_str} ];')
    lines.append("}")
    return "\n".join(lines) + "\n"


def write_secrets_nix(cfg: NixConfig) -> Path:
    if cfg.secrets_nix_path:
        target = Path(cfg.secrets_nix_path)
    else:
        target = Path(cfg.secrets_path) / "secrets.nix"
    content = render_secrets_nix(cfg)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)
    return target
