from __future__ import annotations

import json
import os
from pathlib import Path

import pytest
from click.testing import CliRunner

from agenix_manager.cli import main
from agenix_manager.config import NixConfig

pytestmark = pytest.mark.skipif(
    not os.environ.get("CLI_TESTS"),
    reason="CLI integration tests require CLI_TESTS env var (spawns subprocesses)",
)

FIXTURE = Path(__file__).parent / "fixtures" / "data" / "sample_config.json"


@pytest.fixture
def runner() -> CliRunner:
    return CliRunner()


class TestCliStatus:
    def test_status_via_config_file(self, runner: CliRunner):
        result = runner.invoke(main, ["--config-file", str(FIXTURE), "status"])
        assert result.exit_code == 0
        assert "github-token" in result.output
        assert "db-password" in result.output
        assert "Y" in result.output or "N" in result.output

    def test_status_shows_both_present_and_missing(self, runner: CliRunner):
        result = runner.invoke(main, ["--config-file", str(FIXTURE), "status"])
        assert "github-token" in result.output
        assert "db-password" in result.output


class TestCliSync:
    def test_sync_creates_secrets_nix(self, runner: CliRunner, tmp_path: Path):
        secrets_dir = tmp_path / "secrets"
        secrets_dir.mkdir()
        config = {
            "secrets_path": str(secrets_dir),
            "flake_root": str(tmp_path),
            "identities": ["/etc/ssh/ssh_host_ed25519_key"],
            "keys": {
                "systems": ["ssh-ed25519 AAAA...k"],
                "users": [],
                "other": [],
                "all": ["ssh-ed25519 AAAA...k"],
            },
            "secrets": [
                {"name": "test-sync", "keys": "systems", "file": str(secrets_dir / "test-sync.age")}
            ],
        }
        config_file = tmp_path / "config.json"
        config_file.write_text(json.dumps(config))

        result = runner.invoke(main, ["--config-file", str(config_file), "sync"])
        assert result.exit_code == 0
        secrets_nix = secrets_dir / "secrets.nix"
        assert secrets_nix.exists()
        content = secrets_nix.read_text()
        assert "test-sync.age" in content

    def test_sync_file_starts_with_header(self, runner: CliRunner, tmp_path: Path):
        secrets_dir = tmp_path / "secrets"
        secrets_dir.mkdir()
        config = {
            "secrets_path": str(secrets_dir),
            "flake_root": str(tmp_path),
            "identities": [],
            "keys": {
                "systems": ["ssh-ed25519 AAAA...k"],
                "users": [],
                "other": [],
                "all": ["ssh-ed25519 AAAA...k"],
            },
            "secrets": [{"name": "h", "keys": "systems", "file": str(secrets_dir / "h.age")}],
        }
        config_file = tmp_path / "config.json"
        config_file.write_text(json.dumps(config))
        runner.invoke(main, ["--config-file", str(config_file), "sync"])
        content = (secrets_dir / "secrets.nix").read_text()
        assert content.startswith("# Auto-generated by agenix-manager")


class TestCliExtraIdentity:
    def test_extra_identity_flag_merges(self, runner: CliRunner):
        result = runner.invoke(main, ["--config-file", str(FIXTURE), "-i", "/custom/id", "status"])
        assert result.exit_code == 0

    def test_multiple_extra_identities(self, runner: CliRunner):
        result = runner.invoke(
            main, ["--config-file", str(FIXTURE), "-i", "/id1", "-i", "/id2", "status"]
        )
        assert result.exit_code == 0


class TestCliNixEvalPipeline:
    def test_nix_eval_parse_roundtrip(self, runner: CliRunner):
        raw = json.loads(FIXTURE.read_text())
        cfg = NixConfig.model_validate(raw)
        assert cfg.secrets_path is not None
        assert len(cfg.secrets) > 0


class TestCliHelp:
    def test_help_output(self, runner: CliRunner):
        result = runner.invoke(main, ["--help"])
        assert result.exit_code == 0
        assert "agenix-manager" in result.output
        assert "status" in result.output
        assert "sync" in result.output
        assert "remove" in result.output
        assert "prune" in result.output


class TestCliRemove:
    def test_remove_existing_file(self, runner: CliRunner, tmp_path: Path):
        secrets_dir = tmp_path / "secrets"
        secrets_dir.mkdir()
        age_file = secrets_dir / "test-secret.age"
        age_file.write_text("encrypted")
        config = {
            "secrets_path": str(secrets_dir),
            "flake_root": str(tmp_path),
            "identities": [],
            "keys": {"systems": [], "users": [], "other": [], "all": []},
            "secrets": [{"name": "test-secret", "keys": "all", "file": str(age_file)}],
        }
        config_file = tmp_path / "config.json"
        config_file.write_text(json.dumps(config))
        result = runner.invoke(
            main, ["--config-file", str(config_file), "remove", "test-secret", "--force"]
        )
        assert result.exit_code == 0
        assert "Deleted" in result.output
        assert not age_file.exists()

    def test_remove_missing_file(self, runner: CliRunner, tmp_path: Path):
        secrets_dir = tmp_path / "secrets"
        secrets_dir.mkdir()
        config = {
            "secrets_path": str(secrets_dir),
            "flake_root": str(tmp_path),
            "identities": [],
            "keys": {"systems": [], "users": [], "other": [], "all": []},
            "secrets": [],
        }
        config_file = tmp_path / "config.json"
        config_file.write_text(json.dumps(config))
        result = runner.invoke(
            main, ["--config-file", str(config_file), "remove", "nonexistent", "--force"]
        )
        assert result.exit_code == 0
        assert "No .age file found" in result.output


class TestCliPrune:
    def test_prune_no_orphans(self, runner: CliRunner, tmp_path: Path):
        secrets_dir = tmp_path / "secrets"
        secrets_dir.mkdir()
        config = {
            "secrets_path": str(secrets_dir),
            "flake_root": str(tmp_path),
            "identities": [],
            "keys": {"systems": [], "users": [], "other": [], "all": []},
            "secrets": [],
        }
        config_file = tmp_path / "config.json"
        config_file.write_text(json.dumps(config))
        result = runner.invoke(main, ["--config-file", str(config_file), "prune", "--force"])
        assert result.exit_code == 0
        assert "No orphaned" in result.output

    def test_prune_removes_orphans(self, runner: CliRunner, tmp_path: Path):
        secrets_dir = tmp_path / "secrets"
        secrets_dir.mkdir()
        (secrets_dir / "orphan.age").write_text("encrypted")
        config = {
            "secrets_path": str(secrets_dir),
            "flake_root": str(tmp_path),
            "identities": [],
            "keys": {"systems": [], "users": [], "other": [], "all": []},
            "secrets": [],
        }
        config_file = tmp_path / "config.json"
        config_file.write_text(json.dumps(config))
        result = runner.invoke(main, ["--config-file", str(config_file), "prune", "--force"])
        assert result.exit_code == 0
        assert "Deleted" in result.output
        assert not (secrets_dir / "orphan.age").exists()
