from __future__ import annotations

import json
import subprocess
from pathlib import Path

from agenix_manager.secrets_nix import render_secrets_nix, write_secrets_nix


class TestSecretsNix:
    def test_render_secrets_nix(self, sample_config_with_tmp):
        content = render_secrets_nix(sample_config_with_tmp)
        assert "# Auto-generated by agenix-manager" in content
        assert '"github-token.age".publicKeys' in content
        assert '"db-password.age".publicKeys' in content
        assert content.strip().endswith("}")

    def test_render_keys_correctly(self, sample_config_with_tmp):
        content = render_secrets_nix(sample_config_with_tmp)
        assert '"ssh-ed25519 AAAA...userkey"' in content
        assert '"ssh-ed25519 AAAA...systemkey"' in content

    def test_write_secrets_nix(self, sample_config_with_tmp):
        secrets_dir = Path(sample_config_with_tmp.secrets_path)
        secrets_dir.mkdir(parents=True, exist_ok=True)

        out = write_secrets_nix(sample_config_with_tmp)
        assert out.exists()
        assert out.name == "secrets.nix"
        content = out.read_text()
        assert "github-token.age" in content
        assert "db-password.age" in content

    def test_secrets_nix_syntax_valid_nix(self, sample_config_with_tmp):
        content = render_secrets_nix(sample_config_with_tmp)
        lines = content.strip().split("\n")
        assert lines[0] == "# Auto-generated by agenix-manager -- do not edit by hand."
        assert lines[1] == "{"
        assert lines[-1] == "}"
        for line in lines[2:-1]:
            assert line.strip().endswith(";") or line.strip() == ""

    def test_render_is_valid_nix(self, sample_config_with_tmp):
        content = render_secrets_nix(sample_config_with_tmp)
        tmp = Path("/tmp/test_secrets_nix_valid.nix")
        tmp.write_text(content)
        result = subprocess.run(
            ["nix-instantiate", "--eval", "--strict", str(tmp)],
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, f"nix-instantiate failed: {result.stderr}"

    def test_render_evaluates_to_correct_attrset(self, sample_config_with_tmp):
        content = render_secrets_nix(sample_config_with_tmp)
        tmp = Path("/tmp/test_secrets_nix_eval.nix")
        tmp.write_text(content)
        result = subprocess.run(
            ["nix-instantiate", "--eval", "--strict", "--json", str(tmp)],
            capture_output=True,
            text=True,
            check=True,
        )
        data = json.loads(result.stdout)
        assert "github-token.age" in data
        assert "db-password.age" in data
        assert data["github-token.age"]["publicKeys"] == ["ssh-ed25519 AAAA...userkey"]
        assert len(data["db-password.age"]["publicKeys"]) == 2

    def test_render_literal_key_list(self, sample_config_with_tmp):
        sample_config_with_tmp.secrets[0].keys = ["ssh-ed25519 AAAA...directkey"]
        content = render_secrets_nix(sample_config_with_tmp)
        assert '"ssh-ed25519 AAAA...directkey"' in content
